MDhiringchallenge/config/routes.rb
MDhiringchallenge::Application.routes.draw do
  root to: 'transactions#index'

  resources :customers 
  resources :transactions
  

end

MDhiringchallenge/app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :first_name, :last_name
  has_many :transactions
  validates_presence_of :first_name, :last_name
  def full_name
  	"#{self.first_name} #{self.last_name}"
  end
end

MDhiringchallenge/app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :amount, :currency, :paid, :refunded, :customer_id
  belongs_to :customer
  validates_presence_of :amount, :currency, :paid, :refunded, :customer_id
  
  scope :disputed, -> { where refunded: true }
  scope :successful, -> { where refunded: false, paid: true } 
  scope :failed, -> { where paid: false }

end

MDhiringchallenge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

MDhiringchallenge/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

MDhiringchallenge/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index

    #uninitialized constant TransactionsController::Transactions
    @transactions = Transaction.all

    # Issue
    @successful_transactions = Transaction.successful
    @failed_transactions = Transaction.failed 
    @disputed_transactions = Transaction.disputed
    #@customer = Customer.find_by_id(transaction.customer_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => {
        :transactions => @transactions, 
        :successful_transactions => @successful_transactions,
        :failed_transactions => @failed_transactions,
        :disputed_transactions => @disputed_transactions
        #:customer => @customer
      } 
    }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

MDhiringchallenge/app/helpers/application_helper.rb
module ApplicationHelper
end

MDhiringchallenge/app/helpers/customers_helper.rb
module CustomersHelper
end

MDhiringchallenge/app/helpers/transactions_helper.rb
module TransactionsHelper
end

MDhiringchallenge/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MDhiringchallenge/app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

MDhiringchallenge/app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.first_name %></td>
    <td><%= customer.last_name %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

MDhiringchallenge/app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

MDhiringchallenge/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @customer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @customer.last_name %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

MDhiringchallenge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MDhiringchallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MDhiringchallenge/app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created %><br />
    <%= f.datetime_select :created %>
  </div>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :refunded %><br />
    <%= f.check_box :refunded %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MDhiringchallenge/app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

MDhiringchallenge/app/views/transactions/index.html.erb
<table id="failed">
  <thead><h1>Failed Transactions</h1></thead>
  <tr>
    <th>Date Created</th>
    <th>Paid</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Refunded</th>
    <th>Customer Name</th>
  </tr>
    <% @failed_transactions.each do |transaction| %> 
      <tr class="failed_transaction">
        <td><%= transaction.created_at %></td>
        <td><%= transaction.paid %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.currency %></td>
        <td><%= transaction.refunded %></td>
        <td><%= transaction.customer.full_name %></td>
        <!-- <td><%= Customer.find_by_id(transaction.customer_id).first_name%></td> -->
      </tr>
<% end %>
</table>
</br>

<table id="disputed">
  <thead><h1>Disputed Transactions</h1></thead>
  <tr>
    <th>Date Created</th>
    <th>Paid</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Refunded</th>
  </tr>
    <% @disputed_transactions.each do |transaction| %>
      <tr class="disputed_transaction">
        <td><%= transaction.created_at %></td>
        <td><%= transaction.paid %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.currency %></td>
        <td><%= transaction.refunded %></td>
        <td><%= transaction.customer.full_name %></td>
      </tr>
<% end %>
</table>
</br>

<table id="successful">
  <thead><h1>Successful Transactions</h1></thead>
  <tr>
    <th>Date Created</th>
    <th>Paid</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Refunded</th>
  </tr>
    <% @successful_transactions.each do |transaction| %>
      <tr class="successful_transaction">
        <td><%= transaction.created_at %></td>
        <td><%= transaction.paid %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.currency %></td>
        <td><%= transaction.refunded %></td>
        <td><%= transaction.customer.full_name %></td>
      </tr>
<% end %>
</table>


<br />

<!-- 
<#%= link_to 'New Transaction', new_transaction_path %> 
-->

MDhiringchallenge/app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

MDhiringchallenge/app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Created:</b>
  <%= @transaction.created %>
</p>

<p>
  <b>Paid:</b>
  <%= @transaction.paid %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>

<p>
  <b>Currency:</b>
  <%= @transaction.currency %>
</p>

<p>
  <b>Refunded:</b>
  <%= @transaction.refunded %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>